### ISSUE TITLE
Compound object not working

### ISSUE THREAD

**Issue by snmacfarlane** [UVicLibrary/Spotlight2_custom#6]
Receiving "NoMethodError in Spotlight::Catalog#show" message for compound object 9-14441. 

Should object be deleted and re-added? ID range for objects to include is 9-13523 to 9-13533.

**Comment by eltiffster** [comment]
Thanks, @snmacfarlane! It works now. Funny enough, I was fixing issue #1 and the code mistakenly applied to compound objects, but it shouldn't happen anymore.
